services:
  symfony:
    image: custom_symfony2:latest
    restart: on-failure:3
    volumes:
      - ../:/app
    environment:
      - APP_ENV=dev
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    # depends_on:
    # - postgres
    # command: "echo Symfony service is running..."

  # postgres:
  #   extends:
  #     file: ../database/compose.yml
  #     service: postgres
