version: '3.8'

services:
  adminer:
    build: 
      context: ./adminer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - database

  postgres:
    build: 
      context: ./postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - database

networks:
  database:

volumes:
  pgdata:
