services:
  adminer:
    build:
      context: ./adminer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure:3
    depends_on:
      - postgres

  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure:3

volumes:
  pgsqldata:
# TODO: Dockerfile for postgresql and adminer
