services:
  adminer:
    build:
      context: ./adminer
      dockerfile: Dockerfile
    volumes:
      - socket:/run/postgresql
    ports:
      - "8080:80"
    restart: on-failure:3
    depends_on:
      - postgres
    networks:
      - my-network

  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./postgresql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - pgsqldata:/var/lib/postgresql/data
      - socket:/tmp
    ports:
      - "5432:5432"
    restart: on-failure:3
    env_file:
      - .env
    networks:
      - my-network

networks:
  my-network:
    name: postgres_network

volumes:
  pgsqldata:
  socket:
