services:
  composer:
    build:
      context: .
      target: custom_composer
    tty: true
    volumes:
      - .:/app
    networks:
      - my-network

  symfony:
    build:
      context: .
      target: custom_symfony
    tty: true
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      APP_ENV: dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - composer
    networks:
      - my-network

networks:
  my-network:
    name: postgres_network
    external: true
