services:
  composer:
    build:
      context: .
      target: custom_composer
    restart: on-failure:3
    tty: true
    volumes:
      - .:/app
    networks:
      - my-network

  symfony:
    build:
      context: .
      target: custom_symfony
    restart: on-failure:3
    tty: true
    volumes:
      - .:/app
    environment:
      - APP_ENV=dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - composer
    networks:
      - my-network

networks:
  my-network:
    name: postgres_network
    external: true
