version: '3.8'

services:
    composer:
        build:
            context: .
            dockerfile: Dockerfile.composer
        volumes:
            - .:/app
        working_dir: /app
        command: composer create-project symfony/skeleton symfony_project

    symfony:
        build:
            context: .
            dockerfile: Dockerfile.symfony
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        working_dir: /app
        command: php symfony_project/bin/console server:run 0.0.0.0:8000
        depends_on:
            composer:
                condition: service_completed_successfully
