version: '3.8'

services:
    composer:
        build:
            context: .
            dockerfile: Dockerfile.composer
        volumes:
            - .:/app
        working_dir: /app
        # command: ["composer", "install"]
        networks:
            - my-network

    symfony:
        build:
            context: .
            dockerfile: Dockerfile.symfony
        ports:
            - "8000:8000"
        volumes:
            - .:/app
            - /var/run/docker.sock:/var/run/docker.sock
        working_dir: /app
        networks:
            - my-network
        depends_on:
            - composer

networks:
    my-network: